# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"
#  - "3.4"

env:
  global:
    - TEST_DB_USER="postgres"
  matrix:
    - DJANGO="Django>=1.8,<1.9"
    - DJANGO="Django>=1.7,<1.8"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install $DJANGO
  - pip install -r requirements-test.txt

# command to run tests using coverage, e.g. python setup.py test
script:
  - coverage run --source wlcmanager runtests.py

# report coverage to coveralls.io
before_install:
  - pip install coveralls
#  - pip install codecov
after_success:
  - coveralls -v
#  - codecov

