# Config file for automatic testing at travis-ci.org
sudo: false
language: python

env:
  global:
    - TEST_DB_USER="postgres"
  matrix:
    - TOXENV=py27-django-17
    - TOXENV=py27-django-18
    - TOXENV=py27-django-19
    - TOXENV=py27-django-110

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install tox coveralls

before_script:
  - coverage erase

script: tox

after_success:
  - coveralls -v
#  - codecov

